# .github/workflows/scheduled_bot_run.yml
name: Run Trading Bots Hourly and Commit Log

on:
  schedule:
    # Runs hourly at 8:00 AM Pacific Time - 3 (PDT/PST = UTC-7/UTC-8)
    # 8:00 AM PT = 15:00 UTC (during PDT, UTC-7)
    - cron: '0 15-22 * * 1-5'
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write

jobs:
  run-bots-and-commit-log:
    runs-on: ubuntu-latest
    env:
      BOT_NAME_1: "trading_bot_llm_sentiment_brian"
      BOT_API_KEY_1: ${{ secrets.BOT_API_KEY_1 }}
      BOT_API_SECRET_1: ${{ secrets.BOT_API_SECRET_1 }}

      BOT_NAME_2: "momentum_bot_carlo"
      BOT_API_KEY_2: ${{ secrets.BOT_API_KEY_2 }}
      BOT_API_SECRET_2: ${{ secrets.BOT_API_SECRET_2 }}

      BOT_NAME_3: 'trading_bot_macd_melissa'
      BOT_API_KEY_3: ${{ secrets.BOT_API_KEY_3 }}
      BOT_API_SECRET_3: ${{ secrets.BOT_API_SECRET_3 }}

    steps:
    - name: Check out main branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Pipenv and Dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv sync --system --dev

    - name: Run Bot Manager
      run: python bot_manager.py --run trading_bot_macd_melissa

    - name: Display Log File Content
      if: always()
      run: |
        echo "--- Start of bot_manager.log ---"
        cat bot_manager.log || true
        tail -c 1000 bot_manager.log || true
        echo "--- End of bot_manager.log ---"

    - name: Checkout bot-execution-fast branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: bot-execution-fast

    - name: Commit and Push Log Files
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

        # Only stage .log files
        find . -name "*.log" -exec git add {} +

        if ! git diff --staged --quiet; then
          echo "Changes detected in .log files. Committing..."
          git commit -m "Update bot execution log [skip ci]" -m "Workflow Run ID: ${{ github.run_id }}"
          echo "Pulling latest changes from bot-execution-fast branch..."
          if git pull --rebase origin bot-execution-fast; then
            echo "Checking for log file conflicts..."
            for file in $(git diff --name-only --diff-filter=U | grep '\.log$'); do
              echo "Resolving conflict in $file by keeping local version..."
              git checkout --ours "$file"
              git add "$file"
            done
            git rebase --continue || true
          fi
          echo "Pushing updated log(s) to bot-execution-fast branch..."
          git push origin bot-execution-fast
          echo "Push successful."
        else
          echo "No changes detected in .log files. Nothing to commit."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
